"""
Merge duplicate nodes in a GraphML graph based on their name and type.

This script loads a GraphML network and identifies nodes that share the
same combination of ``name`` and ``type`` attributes. Such nodes are
merged into a single representative node in a new graph.

Nodes without a name are preserved as independent entities and are not
merged. After merging, all edges are reconstructed according to the new
node mapping, avoiding self-loops created by the merge process.

Input:
    - GraphML file containing node attributes ``name`` and ``type``.

Output:
    - A cleaned GraphML file where duplicate entities have been merged.
    - Statistics about the graph before and after the merge process.
"""
import networkx as nx
from collections import defaultdict

# Input GraphML file containing the original network
INPUT_FILE = "tcm_subgraph.graphml"

# Output GraphML file containing the merged network
OUTPUT_FILE = "tcm_subgraph_clean.graphml"

# Load the original graph
G = nx.read_graphml(INPUT_FILE)

# Group nodes by their (name, type) attributes
groups = defaultdict(list)

# Only nodes with a non-empty name are considered for merging.
for node_id, data in G.nodes(data=True):

    name = str(data.get("name", "")).strip()
    node_type = str(data.get("type", "")).strip()

    if name:
        groups[(name, node_type)].append(node_id)

# Create the merged graph.
H = nx.Graph()

# Maps original node IDs to their corresponding node
# in the merged graph.
node_mapping = {}

# Create one representative node for each group of
# nodes sharing the same name and type.
for (name, node_type), ids in groups.items():

    representative = f"{node_type}::{name}"

    H.add_node(
        representative,
        name=name,
        label=name,
        type=node_type
    )

    # Store the mapping from original IDs to the
    # representative node.
    for old_id in ids:
        node_mapping[old_id] = representative

# Copy unnamed nodes without merging them.
for node_id, data in G.nodes(data=True):

    name = str(data.get("name", "")).strip()

    if not name:

        H.add_node(
            str(node_id),
            **data
        )

        node_mapping[node_id] = str(node_id)

# Rebuild edges using the merged node mapping.
# Self-loops generated by merging are discarded.
for u, v in G.edges():

    new_u = node_mapping[u]
    new_v = node_mapping[v]

    if new_u != new_v:
        H.add_edge(new_u, new_v)

# Display graph statistics before and after merging.
print(f"Nodos originales: {G.number_of_nodes()}")
print(f"Aristas originales: {G.number_of_edges()}")
print(f"Nodos después de fusionar: {H.number_of_nodes()}")
print(f"Aristas después de fusionar: {H.number_of_edges()}")

# Export the cleaned graph.
nx.write_graphml(H, OUTPUT_FILE)

print(f"Guardado en {OUTPUT_FILE}")